const menu = [
    {
        id: 1,
        title: 'Vulcan PRO',
        category: 'OpticalSWITCH',
        price: 199.99,
        img: './images/tast1.png',
        desc: `Award Winning Design`,
        desc1: `100 million keystroke life-cycle`,
        desc2: `32-bit ARM Cortex-M0 based processor`,
      },
      {
        id: 2,
        title: 'Vulcan TKL Pro',
        category: 'OpticalSWITCH',
        price: 129.99,
        img: './images/tast2.png',
        desc: `Titan Switch Optical (1.4mm actuation, linear)`,
        desc1: `100 million keystroke life-cycle`,
        desc2: `Compact TKL form factor`,
      },
      {
        id: 3,
        title: "Vulcan TKL",
        category: "OpticalSWITCH",
        price: 129.99,
        img: "./images/tast3.png",
        desc: `Titan Switch Optical (1.4mm actuation, linear)`,
        desc1: `50 million keystroke life-cycle`,
        desc2: `Compact TKL form factor`,
      },
      {
        id: 4,
        title: "Vulcan 122 AIMO",
        category: "MechanicalSWITCH",
        price: 159.99,
        img: "./images/tast4.png",
        desc: `ROCCAT Titan Switches – tactile and crisp brown mechanical switches`,
        desc1: `AIMO illumination – RGB backlighting and LED lighting effects`,
        desc2: `Durable design – robust materials and switches that resist dust build-up`,
      },
      {
        id: 5,
        title: "Vulcan 121 AIMO",
        category: "MechanicalSWITCH",
        price: 119.99,
        img: "./images/tast5.png",
        desc: `ROCCAT Titan Switches – tactile and crisp brown mechanical switches`,
        desc1: `AIMO illumination – RGB backlighting and LED lighting effects`,
        desc2: `Durable design – robust materials and switches that resist dust build-up`,
      },
      {
        id: 6,
        title: 'Vulcan 120 AIMO',
        category: 'MechanicalSWITCH',
        price: 159.99,
        img: './images/tast6.png',
        desc: `ROCCAT Titan Switches – tactile and crisp brown mechanical switches`,
        desc1: `AIMO illumination – RGB backlighting and LED lighting effects`,
        desc2: `Durable design – robust materials and switches that resist dust build-up`,
      },
     
      {
        id: 7,
        title: "Horde AIMO",
        category: "Membrane",
        price: 49.99,
        img: "./images/tast8.webp",
        desc: `Fingertip design keys with improved distinction, island layout that resists dirt`,
        desc1: `Configurable Tuning Wheel for on-the-fly control`,
        desc2: `Membranical keys with precise midway travel actuation point`,
      },
      {
        id: 8,
        title: "Horde",
        category: "Membrane",
        price: 39.99,
        img: "./images/tast9.webp",
        desc: `Fingertip design keys with improved distinction, island layout that resists dirt`,
        desc1: `Configurable Tuning Wheel for on-the-fly control`,
        desc2: `Membranical keys with fast midway travel actuation point`,
      },
  ];
  export default menu;
  