const menu2 = [
    {
      id: 1,
      title: "Elo 7.1 Air",
      category: "Wireless",
      price: 99.99,
      img: "./images/slusalice.png",
      desc: `Wireless surround Sound`,
      desc1: `2.4GHz transmitter frequency response`,
      desc2: `Rechargeable 24h battery32-bit ARM Cortex-M0 based processor`,
    },
    {
      id: 2,
      title: "Elo 7.1 USB",
      category: "Surround",
      price: 69.99,
      img: "./images/headset1.png",
      desc: `Self-adjusting metal headband`,
      desc1: `Removable unidirectional microphone`,
      desc2: `TruSpeak™ microphone technology`,
    },
    {
      id: 3,
      title: "Elo X Stereo",
      category: "Stereo",
      price: 49.99,
      img: "./images/headset2.png",
      desc: `Cross Platform Compatibility`,
      desc1: `Precision-tuned 50mm neodymium drivers`,
      desc2: `Leatherette headband with foam cushioning`,
    },
    {
      id: 4,
      title: "Khan Pro",
      category: "Stereo",
      price: 39.99,
      img: "./images/headset3.png",
      desc: `High resolution sound with drivers that deliver richer highs mids lows`,
      desc1: `Passive noise cancelation works great even in the noisiest of environments`,
      desc2: `Feather light - lightest amongst esports headsets at only 230g`,
    },
    {
      id: 5,
      title: "Noz",
      category: "Stereo",
      price: 29.99,
      img: "./images/headset4.png",
      desc: `Natural Sound`,
      desc1: `Solid Metal hinges`,
      desc2: `only 210 grams`,
    },
  ];
  export default menu2;