const menu1 = [
    {
      id: 1,
      title: "Vulcan PRO",
      category: "Optical",
      price: 199.99,
      img: "./images/mic2.png",
      desc: `Award Winning Design`,
      desc1: `100 million keystroke life-cycle`,
      desc2: `32-bit ARM Cortex-M0 based processor`,
    },
    {
      id: 2,
      title: "Vulcan TKL Pro",
      category: "Wireless",
      price: 129.99,
      img: "./images/mic3.png",
      desc: `Titan Switch Optical (1.4mm actuation, linear)`,
      desc1: `100 million keystroke life-cycle`,
      desc2: `Compact TKL form factor`,
    },
    {
      id: 3,
      title: "Vulcan TKL",
      category: "Optical",
      price: 129.99,
      img: "./images/mic4.png",
      desc: `Titan Switch Optical (1.4mm actuation, linear)`,
      desc1: `50 million keystroke life-cycle`,
      desc2: `Compact TKL form factor`,
    },
    {
      id: 4,
      title: "Vulcan 122 AIMO",
      category: "Optical",
      price: 159.99,
      img: "./images/mic5.png",
      desc: `ROCCAT Titan Switches – tactile and crisp brown mechanical switches`,
      desc1: `AIMO illumination – RGB backlighting and LED lighting effects`,
      desc2: `Durable design – robust materials and switches that resist dust build-up`,
    },
    {
      id: 5,
      title: "Vulcan 121 AIMO",
      category: "Optical",
      price: 119.99,
      img: "./images/mic6.png",
      desc: `ROCCAT Titan Switches – tactile and crisp brown mechanical switches`,
      desc1: `AIMO illumination – RGB backlighting and LED lighting effects`,
      desc2: `Durable design – robust materials and switches that resist dust build-up`,
    },
    {
      id: 6,
      title: "Vulcan 120 AIMO",
      category: "Wireless",
      price: 159.99,
      img: "./images/mic7.png",
      desc: `ROCCAT Titan Switches – tactile and crisp brown mechanical switches`,
      desc1: `AIMO illumination – RGB backlighting and LED lighting effects`,
      desc2: `Durable design – robust materials and switches that resist dust build-up`,
    },
    {
      id: 7,
      title: "Vulcan 100 AIMO",
      category: "Optical",
      price: 149.99,
      img: "./images/mic8.png",
      desc: `ROCCAT Titan Switches – tactile and crisp brown mechanical switches`,
      desc1: `AIMO illumination – RGB backlighting and LED lighting effects`,
      desc2: `Durable design – robust materials and switches that resist dust build-up`,
    },
    {
      id: 8,
      title: "Horde AIMO",
      category: "Optical",
      price: 49.99,
      img: "./images/mic9.png",
      desc: `Fingertip design keys with improved distinction, island layout that resists dirt`,
      desc1: `Configurable Tuning Wheel for on-the-fly control`,
      desc2: `Membranical keys with precise midway travel actuation point`,
    },
   
   
  ];
  export default menu1;